services:
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"

  phpmyadmin:
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - "/sessions"
      - "./docker/phpmyadmin/conf.d:/usr/local/etc/php/conf.d"

  nginx:
    restart: always
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./:/var/www/html"
      - "./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./docker/nginx/log:/var/log/nginx/"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - phpfpm
    links:
      - phpfpm

  phpfpm:
    build: ./docker/phpfpm/
    ports:
      - "9000:9000"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./:/var/www/html"
      - "./docker/phpfpm/conf:/usr/local/etc/php"
    depends_on:
      - mysql
    links:
      - mysql
    mem_limit: 1G
    mem_reservation: 512M

volumes:
  db_data:
